module Rule
  BLACKJACK_NUM = 21
  ADJUST_NUM = 10
  BLACKJACK_HAND_CARDS_SIZE = 2
  BLACKJACK_POINT_LIST_SIZE = 2
  STATUS_BLACKJACK = 0
  STATUS_BUST = 1
  STOP_DRAWING_NUM = 17
  RATE_BLACKJACK = 2.5
  RATE_NORMAL_WIN = 2
  RATE_TIE = 1
  RATE_LOSE = 0
end
