module Rule
  BLACKJACK_NUM = 21
  ADJUST_NUM = 10
  BLACKJACK_HAND_CARDS_SIZE = 2
  BLACKJACK_POINT_LIST_SIZE = 2
  BLACKJACK = 0
  BUST = 1
  HIT_NUM = 1
  STAND_NUM = 2
  STOP_DRAWING_NUM = 17
  WIN = 1
  LOSE = 0
  BLACKJACK_RATE = 2.5
  NORMAL_WIN_RATE = 2
  TIE_RATE = 1
  LOSE_RATE = 0
  GAME_CONTINUE_NUM = 1
  GAME_END_NUM = 2
end
